### PR TITLE
Created models for Order and ProductOrder

### PR DESCRIPTION
**Pull request by jacklynknight08**
## Status
**READY**

## Migrations
NO

## Description
I've created a model in Order.cs to create a table for all orders in the database. I created a ProductOrder.cs file to set up a model to create a table to hold both products and orders. These files will help in seeding our database from the DBInitializer file.

## Related PRs
List related PRs against other branches: None

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Resolves Issue Number
number [link]()

## Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
git checkout master
git fetch --all
git checkout jk-orderModel
git pull origin jk-orderModel
```
## Impacted Areas in Application
List general components of the application that this PR will affect:

* Order.cs
* ProductOrder.cs

### CODE REVIEW

**Comment by ollieOsh** [comment]
👍

**Comment by ollieOsh** [comment]
😈

**Comment by ollieOsh** [comment]
antichrist

**Comment by joeybiotti** [comment]
🤢

**Pull request merged**
